import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [showMe, setShowMe] = useState(false);

  return (
    <>
      <Head>
        <title>Conventional Emoji Commit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: showMe ? "block" : "none",
        }}
      >
        <div
          aria-live="assertive"
          className="fixed inset-0 flex items-start px-4 py-6 pointer-events-none sm:p-6"
        >
          <div className="w-full flex flex-col items-center space-y-4 sm:items-start">
            <div className="max-w-sm w-full bg-white shadow-lg rounded-lg pointer-events-auto ring-1 ring-black ring-opacity-5 overflow-hidden">
              <div className="p-4">
                <div className="flex items-center">
                  <div className="w-0 flex-1 flex justify-between">
                    <p className="w-0 flex-1 text-sm font-medium text-gray-900">
                      Version - 1.0.0
                    </p>
                  </div>
                  <div className="ml-4 flex-shrink-0 flex">
                    <button
                      type="button"
                      className="bg-white rounded-md inline-flex text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                      onClick={() => setShowMe(!showMe)}
                    >
                      <span className="sr-only">Close</span>
                      <svg
                        className="h-5 w-5"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20"
                        fill="currentColor"
                        aria-hidden="true"
                      >
                        <path
                          fillRule="evenodd"
                          d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                          clipRule="evenodd"
                        />
                      </svg>
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="w-screen h-screen bg-gradient-to-l from-cyan-500 to-blue-500">
        <div className="max-w-4xl m-auto px-4 flex flex-row justify-end">
          <div className="px-3 mx-4 text-white font-normal my-3 py-4">
            <button onClick={() => setShowMe(!showMe)}>Version</button>
          </div>
          <div className="px-3 mx-4 text-white font-normal my-3 py-4">
            <a target="_blank" href="https://filippobrigati.vercel.app/">
              About
            </a>
          </div>
        </div>
        <div className="max-w-4xl m-auto p-4 bg-transparent flex items-center h-4/5">
          <div className="flex-flex-col">
            <p className="text-white font-semibold text-5xl sm:text-6xl">
              Conventional Emoji Commit
            </p>
            <p className="bg-trasparent text-white text-lg font-normal mt-3">
              A specification for adding a readable meaning to commit messages
              with emoji
            </p>
            <div className="mt-6">
              <a
                type="button"
                className="mr-4 inline-flex items-center px-4 py-2 border border-white text-sm font-medium rounded-md text-white bg-trasparent focus:outline-none focus:ring-2 hover:bg-white hover:text-gray-700"
                href="#summary"
              >
                Summary
              </a>
              <a
                type="button"
                className="mr-4 inline-flex items-center px-4 py-2 border border-white text-sm font-medium rounded-md text-white bg-trasparent focus:outline-none focus:ring-2 hover:bg-white hover:text-gray-700"
                href="#documentation"
              >
                Documentation
              </a>
              <a
                type="button"
                className="mr-4 mt-4 sm:mt-0 inline-flex items-center px-4 py-2 border border-white text-sm font-medium rounded-md text-white bg-trasparent focus:outline-none focus:ring-2 hover:bg-white hover:text-gray-700"
                target="_blank"
                href="https://github.com/filippo-brigati/conventional-emoji-commit"
              >
                Contribute
              </a>
            </div>
          </div>
        </div>
        <div className="max-w-5xl bg-white border-none rounded-md m-auto shadow-lg">
          <div className="py-6 px-8 sm:px-14">
            <p className="text-blue-500 font-semibold text-3xl">
              Conventional 😀 Commit 1.0.0
            </p>
            <hr className="my-4 border border-b-1 border-blue-200"></hr>
            <p className="text-blue-500 font-semibold text-2xl" id="summary">
              Summary
            </p>
            <p className="font-normal text-gray-700 leading-relaxed mt-3">
              The Conventional Emoji Commits is a convention on top of commit
              messages. It provides an easy set of rules for creating an
              explicit commit history. Emojis are used to ensure more immediate
              readability. <br></br>
            </p>
            <p className="font-normal text-gray-700 leading-relaxed mt-3">
              The commit message should be structured as follows:
            </p>
            <div className="bg-gray-100 rounded-md text-gray-800 py-4 px-6 mt-4">
              {"<emoji> <type>: <description>"}
            </div>
            <hr className="my-4 border border-b-1 border-blue-200"></hr>
            <p
              className="text-blue-500 font-semibold text-2xl"
              id="documentation"
            >
              Documentation
            </p>
            <p className="font-normal text-gray-700 leading-relaxed mt-3">
              The following list explains some of the{" "}
              <span className="p-1 rounded-md bg-gray-100">{"<type>"}</span> of
              commit:
            </p>
            <ol className="list-decimal list-inside ml-2 text-gray-700 leading-relaxed">
              <li className="mt-2">
                <span className="font-semibold text-gray-800">📈 feat: </span>
                the commit of the <span className="italic">type</span> feat add
                new items or features to the project.
              </li>
              <li className="mt-2">
                <span className="font-semibold text-gray-800">⛏ fix: </span>
                the commit of the <span className="italic">type</span> fix is
                used when you fix a bug or resolve an issue.
              </li>
              <li className="mt-2">
                <span className="font-semibold text-gray-800">
                  ♻️ refactor:{" "}
                </span>
                the commit of the <span className="italic">type</span> refactor
                is used when you rewrite part of / all a feature or you chenge a
                lot of code to the project.
              </li>
              <li className="mt-2">
                <span className="font-semibold text-gray-800">📚 docs: </span>
                the commit of the <span className="italic">type</span> docs is
                used when you change the docs {" (readme.md) "} of your project.
              </li>
              <li className="mt-2">
                <span className="font-semibold text-gray-800">✨ style: </span>
                the commit of the <span className="italic">type</span> style is
                used when you format the code or you beautify it.
              </li>
              <li className="mt-2">
                <span className="font-semibold text-gray-800">🚦 test: </span>
                the commit of the <span className="italic">type</span> test is
                used for adding missing tests, refactoring tests; no production
                code change.
              </li>
              <li className="mt-2">
                <span className="font-semibold text-gray-800">☄️ chore: </span>
                the commit of the <span className="italic">type</span> chore is
                used for updating grunt tasks etc; no production code change.
              </li>
            </ol>
            <div className="px-4 sm:px-6 lg:px-8">
              <div className="mt-8 flex flex-col">
                <div className="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
                  <div className="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
                    <div className="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
                      <table className="min-w-full divide-y divide-blue-300">
                        <thead className="bg-blue-50">
                          <tr>
                            <th
                              scope="col"
                              className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6"
                            >
                              EMOJI
                            </th>
                            <th
                              scope="col"
                              className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"
                            >
                              TYPE
                            </th>
                            <th
                              scope="col"
                              className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"
                            >
                              EXAMPLE
                            </th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-200 bg-white">
                          <tr>
                            <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                              📈
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                              feat
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                              📈 feat: new login page, added services...
                            </td>
                          </tr>
                          <tr>
                            <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                              ⛏
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                              fix
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                              ⛏ fix: login services, table overflow on mobile...
                            </td>
                          </tr>
                          <tr>
                            <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                              ♻️
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                              refactore
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                              ♻️ refactore: login pages, navbar component, list
                              component...
                            </td>
                          </tr>
                          <tr>
                            <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                              📚
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                              docs
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                              📚 docs: updated documentation, new README.MD...
                            </td>
                          </tr>
                          <tr>
                            <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                              ✨
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                              style
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                              ✨ style: code formatted using prettier...
                            </td>
                          </tr>
                          <tr>
                            <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                              🚦
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                              test
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                              🚦 test: testing new login pages for production...
                            </td>
                          </tr>
                          <tr>
                            <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                              ☄️
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                              chore
                            </td>
                            <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                              ☄️ chore: updating all grunt tasks...
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
