import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Conventional Emoji Commit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen h-screen bg-gradient-to-l from-cyan-500 to-blue-500">
        <div className="max-w-5xl m-auto px-4 flex flex-row justify-end">
          <div className="px-3 mx-4 uppercase text-white font-normal my-3 py-4">
            Version
          </div>
          <div className="px-3 mx-4 uppercase text-white font-normal my-3 py-4">
            About
          </div>
          <div className="px-3 mx-4 uppercase text-white font-normal my-3 py-4">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-6 w-6"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth="2"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"
              />
            </svg>
          </div>
        </div>
        <div className="max-w-4xl m-auto p-4 bg-transparent flex items-center h-4/5">
          <div className="flex-flex-col">
            <p className="text-white font-semibold text-5xl sm:text-6xl">
              Conventional Emoji Commit
            </p>
            <p className="bg-trasparent text-white text-lg font-normal mt-3">
              A specification for adding a readable meaning to commit messages
              with emoji
            </p>
            <div className="mt-6">
              <button
                type="button"
                className="mr-4 inline-flex items-center px-4 py-2 border border-white text-sm font-medium rounded-md text-white bg-trasparent focus:outline-none focus:ring-2"
              >
                Button text
              </button>
              <button
                type="button"
                className="mr-4 inline-flex items-center px-4 py-2 border border-white text-sm font-medium rounded-md text-white bg-trasparent focus:outline-none focus:ring-2"
              >
                Button text
              </button>
              <button
                type="button"
                className="mr-4 inline-flex items-center px-4 py-2 border border-white text-sm font-medium rounded-md text-white bg-trasparent focus:outline-none focus:ring-2"
              >
                Button text
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
